quarkus.datasource.db-kind=oracle
quarkus.datasource.username=system
quarkus.datasource.password=123
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1

%prod.quarkus.datasource.jdbc.url=jdbc:oracle:thin:@database:1521/FREEPDB1

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.dialect=org.hibernate.dialect.OracleDialect

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

%dev.quarkus.hibernate-orm.schema-management.strategy = drop-and-create
%dev.quarkus.hibernate-orm.sql-load-script = import.sql

%dev-with-data.quarkus.hibernate-orm.schema-management.strategy = update
%dev-with-data.quarkus.hibernate-orm.sql-load-script = no-file

%prod.quarkus.hibernate-orm.database.generation = drop-and-create
%prod.quarkus.hibernate-orm.sql-load-script = import.sql

%prod-with-data.quarkus.hibernate-orm.database.generation = update
%prod-with-data.quarkus.hibernate-orm.sql-load-script = import.sql